### ISSUE TITLE
Variant: attempting to use incompatible types immutable(char)[] and int

### ISSUE THREAD

**Issue by bubnenkoff** [Abscissa/mysql-native-experimental#3]
As I understood we get data from DB in `Variant` format. How I can convert it to standard D data types?

I tried:
Row row = result.front;
user.id = row[1].get!int;

and got error: `Variant: attempting to use incompatible types immutable(char)[] and int`

I found way:
`user.id = row[1].convertsTo!(int);`
But can't understand if I used it's as intended?

**Comment by Abscissa** [comment]
Variant is part of D's standard library (Phobos). It's documented here: http://dlang.org/phobos/std_variant.html

That error means the second column is a string, not an int. Store it in a string, or if you need it converted use the data conversion functions in Phobos.

**Comment by bubnenkoff** [comment]
Ok, but what is the difference between `to!string` and `convertsTo!(string)`  which one is better and why?

**Comment by Abscissa** [comment]
That's more a question for the [D newsgroup](http://forum.dlang.org/group/learn).
