### ISSUE TITLE
get array of rows

### ISSUE THREAD

**Issue by bubnenkoff** [Abscissa/mysql-native-experimental#7]
What is the best practice to get from DB array of rows? Only foreach loop? Like:

```
Row rows = result.front;
foreach(row; rows)
x = row[0]
y = row[1]
....
```
Or is there any better (native way)?

upd: I tried, but get next error:
![default](https://cloud.githubusercontent.com/assets/6514326/22943538/f49f9e20-f2fe-11e6-9866-7add4b1aa3b3.png)

Examples of getting single entry show:
`Row row = result.front;`
what `result.front;` is means here?

P.S. Big thanks for you driver!

**Comment by Abscissa** [comment]
You're trying to loop over the first Row (singular). That's why it's not working. You may want to look into D's ranges and how they work: http://ddili.org/ders/d.en/ranges.html http://www.informit.com/articles/article.aspx?p=1407357

**Comment by bubnenkoff** [comment]
I looked :(
Could you show an example.


чт, 16 февр. 2017 г. в 7:42, Nick Sabalausky <notifications@github.com>:

**Comment by Abscissa** [comment]
foreach(row; result)

**Comment by bubnenkoff** [comment]
Thanks!
