### ISSUE TITLE
Row schema support

### ISSUE THREAD

**Issue by aberba** [Abscissa/mysql-native-experimental#9]
It can be very covenient to have schema for binding to row fetched from DB like:

```d
// structured row annotations
	struct PlaceFull {
		uint id;
		string name;
		@optional string thumbnail;	// ok to be null or missing
		@optional GeoRef location;	// nested fields ok to be null or missing
		@optional @as("contact_person") string contact; // optional, and sourced from field contact_person instead

		@ignore File tumbnail;	// completely ignored
	}
```

And used as:
```d
// after fetchning
auto place = row.toStruct!PlaceFull;
```

furthure
```d
// automated struct member uncamelcase
	@uncamel struct PlaceOwner {
		uint placeID;			// matches placeID and place_id
		uint locationId;		// matches locationId and location_id
		string ownerFirstName;	// matches ownerFirstName and owner_first_name
		string ownerLastName;	// matches ownerLastName and owner_last_name
		string feedURL;			// matches feedURL and feed_url
	}
```

**Comment by Abscissa** [comment]
Yea, that would be a nice thing to have. I'm undecided whether it would belong in mysql-native or in a higher-level library (although at the moment, I'm leaning in favor of it). But in any case, would you mind reposting this issue over [at the main mysql-native issues list](https://github.com/mysql-d/mysql-native/issues)​? This repo here is just a fork for working out the big changes for v1.0.0 (in case I would have needed to totally redo the redesign), and I don't want to loose this issue once this fork gets merged back into the mainline.

**Comment by aberba** [comment]
Ok. Will do that this evening.

**Comment by Abscissa** [comment]
Thanks!
